lzc-sdk-version: "0.1"
name: 极速箱
package: cloud.lazycat.app.jisuxiang
version: 0.0.1
description: 高效开发工具集成平台
homepage: https://github.com/star7th/jisuxiang
author: star7th
application:
  subdomain: jisuxiang
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  public_path:
    - /
  routes:
    - /=http://jisuxiang:3000/
services:
  jisuxiang:
    image: registry.lazycat.cloud/czyt/star7th/jisuxiang:673f56a72c6bb2a7
